### ISSUE TITLE
Source and Target connections must refer to different Dataverse instances

### ISSUE THREAD

**Issue by MK4515** [rsousa88/DataMigrationTool#1]
when trying to connect different instances of the same tenant getting error

**Comment by rsousa88** [comment]
what type of connection are you using?

**Comment by MK4515** [comment]
Connection wizard and i am able to connect other plugins like webresource 
Getting this issue when trying to connect the target source

**Comment by rsousa88** [comment]
Thanks for your feedback. We look for equality on ConnectedOrgId between source and target, this should be different for each instance. I'll look into it later today.

**Comment by MK4515** [comment]
OK thanks

**Comment by rsousa88** [comment]
You need to wait for the update to be listed in XrmToolbox. It should be there by now, can you update and see if it resolved your issue?

**Comment by MK4515** [comment]
Thanks, new update worked
