### ISSUE TITLE
Error:  The user name is required.

### ISSUE THREAD

**Issue by mawankhade** [rsousa88/DataMigrationTool#10]
Hi ,
I am getting below when I am trying to import data using generated JSON.
"Error:  The user name is required"
Any idea what must be causing it?

**Comment by rsousa88** [comment]
Hi @mawankhade,

At first, this doesn't look like a bug on the plugin. Can you please provide more details (log file and/or print screens)?

Also, from which table are importing? Just by looking at the error message, it looks like you are missing a username field, and that field is system required.
