### ISSUE TITLE
Error: Import a Whole Number field

### ISSUE THREAD

**Issue by hoangsang95** [rsousa88/DataMigrationTool#11]
Hi,

When i import a Whole Number field cause error "Incorrect attribute value type System.Int64" because it used Int64 instead Int32 (
JsonConvert will use Int64 to deserialize integer type).

Can you fix this issue?

Thanks & regards!

**Comment by Kejspr** [comment]
@dw-1983 hi how can i install yor version  im newbie and i can't install your updated version
thx

**Comment by rsousa88** [comment]
hey guys, sorry for the delay on this, I don't have much time for this lately.

PR #12 looks good and the issue should be fixed on the next release.

**Comment by rsousa88** [comment]
This and other issues have been resolved on the new release, please update to version 2023.4.20.2 through XrmToolbox:
![image](https://user-images.githubusercontent.com/17320104/233442549-3da5ae22-7b07-4239-b365-f346814508d0.png)
