### ISSUE TITLE
Import of date/time fields failing

### ISSUE THREAD

**Issue by mkeeley23** [rsousa88/DataMigrationTool#5]
When importing an exported data set where one of the attributes is a date, the import of that row generates an error.

- Row error: "ERROR: Incorrect attribute value type System.String"
- key-value pair that, when removed, allows import to succeed (leaving the field below null in target)   {
            "key": "fakeprefix_dateoflastcontact",
            "value": "/Date(1649332800000)/"
}

- failing attribute schema definition:
    - Data Type: Date and Time
    - Field Type: Simple
    - Behavior: User Local
    - Format: Date and Time
    - IME Mode: auto

Edited to add: THANK YOU for this great tool. I particularly enjoy the ability to export to json, where reference data can be added to a code repository for safe-keeping. Thanks again!

**Comment by rsousa88** [comment]
Hi @mkeeley23,

Thanks for your feedback, I'll look into it.

I'll leave this thread open and post here an update when I push a fix.
