### ISSUE TITLE
Error when importing a Team synchronized on an Azure Security Group

### ISSUE THREAD

**Issue by JMG74** [rsousa88/DataMigrationTool#6]
On my DEV environment, I have a Team being synchronized on an Azure Security Group.
I've exported its data and got a file called team.json.
When I try to import it with no change on my target environment (where it does not yet exists), I'm getting the following error:

> ERROR: Type Mismatch: Type of Attribute: Team.azureactivedirectoryobjectid is: System.Guid. However, Type of passed-in value is: System.String;

I'm getting the same behaviour anytime I'm trying to export, then import a Team being synchronized on an Azure Security Group.

Thks for your help. Regards

**Comment by rsousa88** [comment]
Fixed on version 2022.5.12.4

You might need to re-export your data again, as the output files from older versions aren't fully compatible with the new version

**Comment by JMG74** [comment]
Hi rsousa88, 
It works like a charm !! 
Thank you very much for this fix ! 
All the best.
