### ISSUE TITLE
Impossible to export table teamroles

### ISSUE THREAD

**Issue by JMG74** [rsousa88/DataMigrationTool#8]
Hi, 

In the context of a deployment from DEV-->UAT, I would like to export/import the content of table **teamroles** .
As I cannot find this table in the list of available tables, does it mean that this export is forbidden ? if so, why ? and would it be possible to add this features ?

Many thanks in advance.

**Comment by rsousa88** [comment]
Hi @JMG74,

Dynamics doesn't allow direct CRUD operations on teamroles table, which means that we cannot create or update its records.

Nevertheless, I've removed the previous filtering and it is now possible to export data from these tables. Unfortunately you cannot import it, as you will get an error from dynamics saying that the operation is unsupported.

You can check it out on new version 2022.5.23.1
