### ISSUE TITLE
Request to export table columns where IsValidForCreate == false

### ISSUE THREAD

**Issue by ThomasOchsenbein** [rsousa88/DataMigrationTool#9]
Hi Rui,

Thank you for creating a data export to JSON plugin for XrmToolBox.
When I export from the Case (incident) table, the list of columns/attributes has "Status Reason" (statuscode), but it does not have "Status" (statecode).
My understanding is this is because column "Status" has IsValidForCreate == false.
Could I please ask the reason DataMigrationTool does not export columns that have IsValidForCreate == false?
Considering that IsValidForUpdate == true, the data should be exportable for future update of the record.
If a person wants to import the data into another system, the "Status" column is obviously very important and should be exportable.

I believe the relevant c# code is in DataMigrationControl.cs (see below).
Would it be possible to please remove the line:  ` .Where(att => att.IsValidForCreate != null && att.IsValidForCreate.Value)`

Kind Regards,

Thomas

 DataMigrationControl.cs:
```
                    // filter valid attributes
                    args.Result = tableData.Metadata.Attributes
                        .Where(att => att.IsValidForRead != null && att.IsValidForRead.Value)
                        .Where(att => att.IsValidForCreate != null && att.IsValidForCreate.Value)
                        .Where(att => att.DisplayName != null && att.DisplayName.UserLocalizedLabel != null && !string.IsNullOrEmpty(att.DisplayName.UserLocalizedLabel.Label))
                        .Select(att => new Models.Attribute
                        {
                            Type = att.AttributeTypeName.Value.EndsWith("Type") ? att.AttributeTypeName.Value.Substring(0, att.AttributeTypeName.Value.LastIndexOf("Type")) : att.AttributeTypeName.Value,
                            LogicalName = att.LogicalName,
                            DisplayName = att.DisplayName.UserLocalizedLabel.Label,
                            Updatable = att.IsValidForUpdate.Value
                        })
                        .ToList();


```
![Data Migration Tool - Case list of attributes does not have statecode](https://user-images.githubusercontent.com/60331200/169753546-77983de0-4069-4885-acc2-9963641a596f.png)

**Comment by rsousa88** [comment]
Hi @ThomasOchsenbein, thanks for your feedback.

I've removed that limitation on version 2022.5.23.1

I've also added a new setting for showing/hidding these invalid attributes

**Comment by ThomasOchsenbein** [comment]
Thank you @rsousa88, brilliant work
